apiVersion: v1
kind: Secret
metadata:
  name: emprole-secrets
  namespace: emprole
type: Opaque
stringData:
  MONGODB_URI: "replace-with-your-mongodb-uri"
  JWT_SECRET: "replace-with-your-jwt-secret"
